### Create new match
POST http://localhost:2222/matches
Content-Type: application/json

{
    "straightsAllowed": false,
    "bestOf": 7,
    "timeControl": 15
}

### Get one match by id
GET http://localhost:2222/matches/69d17643ecf9f820558a7759

### Get all matches
GET http://localhost:2222/matches

### Update match by id
PATCH http://localhost:2222/matches/69d17944762e51ebf2ebf469
Content-Type: application/json

{
    "isDraw": true
}

### Delete match by id
DELETE http://localhost:2222/matches/69d17944762e51ebf2ebf469
Role: admin