### Create tournament
POST http://localhost:2222/tournaments
Content-Type: application/json
Role: admin

{
    "title": "NTNU Cup",
    "description": "For the best",
    "straightsAllowed": true,
    "bestOf": 7,
    "timeControl": 5,
    "startDate": "2026-05-10",
    "endDate": "2026-05-15",
    "createdBy": "69d14e469df15ebb6aa10a8f"
}

### Get all tournaments
GET http://localhost:2222/tournaments


### Get one tournament by id
GET http://localhost:2222/tournaments/69d1797f762e51ebf2ebf46b

### Join tournament
POST http://localhost:2222/tournaments/69d1797f762e51ebf2ebf46b/join
Content-Type: application/json
Role: user

{
    "userId": "69d14e469df15ebb6aa10a8f"
}

### Delete tournament
DELETE http://localhost:2222/tournaments/69d1797f762e51ebf2ebf46b
Role: admin