export const MIN_USER_USERNAME_LENGTH = 1;
export const MAX_USER_USERNAME_LENGTH = 32;
export const MIN_USER_PASSWORD_LENGTH = 8;
export const MAX_USER_PASSWORD_LENGTH = 64;
export const MIN_USER_AGE_LENGTH = 18;
export const MAX_USER_AGE_LENGTH = 100;
export const DEFAULT_USER_ELO_RATING = 1000;
export const MAX_USER_BIO_LENGTH = 300;


export const MIN_TOURNAMENT_TITLE_LENGTH = 6;
export const MAX_TOURNAMENT_TITLE_LENGTH = 64;
export const MIN_TOURNAMENT_DESCRIPTION_LENGTH = 4;
export const MAX_TOURNAMENT_DESCRIPTION_LENGTH = 500;

export const MIN_COMMENT_LENGTH = 2; 
export const MAX_COMMENT_LENGTH = 500;

