import styles from './AboutUs.module.css';
export default function AboutUs(){
    return(
        <article className={styles.aboutUsWrapper}>
            <div className={styles.aboutContainer}>
                <h1>About Us</h1>
                <p>
                    Spanish Dice Poker is a competitive dice game that combines elements of poker hand rankings with the fast-paced nature of dice rolling. Players take turns rolling and holding dice to build the strongest possible hand, with straights, pairs, and other familiar combinations determining the winner. Each match is a best-of series with a time limit per round, keeping the gameplay intense and strategic.
                </p>
                <p>
                    This platform was designed and built by Emil Larsen, a second year student at NTNU Gjøvik. The project features Elo-based matchmaking, a game lobby where players can create and join games. Whether you're a registered player looking to climb the rankings or just dropping in for a quick anonymous match, there's always a seat at the table.
                </p>
                <span>This text is generated by Ai</span>
            </div>
        </article>
    );
};